openapi: 3.0.0
info:
  title: UserService
  version: 1.0.0
paths:
  /api/user/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  age:
                    type: string
                required:
                  - id
                  - name
                  - age
