name: Pact Provider (Bi-directional with OpenAPI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-provider-contract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Publish OpenAPI Spec to Pact Broker
        run: |
          npx @pact-foundation/pact-cli publish-provider-contract \
            pact/openapi.yaml \
            --provider="UserService" \
            --provider-app-version="${{ github.sha }}" \
            --branch="${{ github.ref_name }}" \
            --content-type="application/yaml" \
            --verification-success \
            --verification-success-published-url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}



