name: Pact Verify Provider

on:
  push:
    branches: [main]

jobs:
  pact-verification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: npm install
      
      - name: Start Provider API
        run: |
          npm run start & # Start your Express server in background
          sleep 5         # Wait a few seconds for server to boot

      - name: Run Pact Provider Verification
        run: npm run test:provider
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
