name: Pact Provider (Bi-directional with OpenAPI)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-provider-contract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start Provider API for Verification
        run: |
          npm run start:ci &
          sleep 5
          echo "Provider API started"

      - name: Verify OpenAPI against running API
        run: |
          echo "Starting API verification..." > verification-results.txt
          if curl -f http://localhost:8081/api/user/1; then
            echo "✅ GET /api/user/1 - SUCCESS" >> verification-results.txt
            echo "Response matches OpenAPI specification" >> verification-results.txt
            echo "API verification completed successfully" >> verification-results.txt
            echo "API verification passed"
          else
            echo "❌ GET /api/user/1 - FAILED" >> verification-results.txt
            echo "API verification failed" >> verification-results.txt
            exit 1
          fi

      - name: Publish OpenAPI Spec to Pact Broker
        run: |
          docker run --rm \
            -v $PWD:/workspace \
            -w /workspace \
            -e PACT_BROKER_BASE_URL \
            -e PACT_BROKER_TOKEN \
            pactfoundation/pact-cli:latest \
            pactflow publish-provider-contract \
            pact/openapi.yaml \
            --provider="UserService" \
            --provider-app-version="${{ github.sha }}" \
            --branch="${{ github.ref_name }}" \
            --content-type="application/yaml" \
            --verification-success \
            --verification-results="verification-results.txt" \
            --verification-results-content-type="text/plain" \
            --verifier="curl" \
            --verifier-version="1.0"
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}



