name: Pact Verify Provider (Bi-directional)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pact-verification:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Start Provider API
        run: |
          npm run start:ci &
          sleep 5
          echo "Provider API started"

      - name: Health Check
        run: |
          curl -f http://localhost:8081/api/user/1 || exit 1
          echo "Health check passed"

      - name: Run Pact Provider Verification Tests
        run: npm run test:provider
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          PROVIDER_VERSION: ${{ github.sha }}
          PROVIDER_BRANCH: ${{ github.ref_name }}



